name: Bingo
version: '1.0'
main: dev.boecker.cherrycave.bingo.BingoPlugin
description: Bingo Game :)
api-version: '26.1.2'
loader: dev.boecker.cherrycave.bingo.BingoPluginLoader
bootstrapper: dev.boecker.cherrycave.bingo.BingoPluginBootstrap
dependencies:
  server:
    SimpleLuckPermsFormatter:
      load: BEFORE
      required: false
      join-classpath: true